#!/usr/bin/env python3
# trade test for Epitech

import Bot

def main():
    bot = Bot.Bot();
    with open("test_data1") as file_in:
        for line in file_in:
            bot.sendLine(line)
    bot.sendLine("action order 2000")
    if (bot.algo == -1):
        return 1
    return 0

main()
